#!/bin/sh
# Netmon Nodewatcher (C) 2010-2011 Freifunk Oldenburg
# Update from Wermelskirchen by RubenKelevra 2012-2015 - cyrond@gmail.com
# Lizenz: GPL / AGPL 3.0
MESH_INTERFACE="br-freifunk"
ADHOC_INTERFACE="wlan0-1"
CLIENT_INTERFACE="wlan0"
BRCTL="/bin/brctl_ff"
WORK_FOLDER="/tmp/"
BASIC_FILENAME="fnetstat"

#check if unique boot-hash has been generated
if [ ! -f "$WORK_FOLDER$BASIC_FILENAME" ]; then
	echo $(head -1 /dev/urandom | md5sum | awk '{ print $1 }') > "$WORK_FOLDER$BASIC_FILENAME" | true
fi

echo "{"

echo "\"sys:script\": \"v0.5\","
echo "\"type\": \"daily\","
#hostnamen ausgeben
output=`cat /proc/sys/kernel/hostname`
echo "\"sys:hostname\": \"$output\","
#unique boot-hash 
output=`cat /tmp/fnetstat`
echo "\"sys:boot_id\": \"$output\","
#BATMAN MAC-Address
output=`ifconfig $ADHOC_INTERFACE | grep 'HWaddr' | awk '{ print $5}'`
echo "\"batman:mac\": \"$output\","
#AP MAC-Address
output=`ifconfig $CLIENT_INTERFACE | grep 'HWaddr' | awk '{ print $5}'`
echo "\"ap:mac\": \"$output\","
#HW-ID
output=`ifconfig eth0 | grep 'HWaddr' | sed "s/^[ ]*//" | awk '{ print $5}' | sed 's/://g'`
echo "\"sys:hwid\": \"$output\","
output=""
[ $(uci get fastd.ffmesh.secret) != 'generate' ] && output=$(/etc/init.d/fastd show_key ffmesh)
echo "\"fastd:pubkey\": \"$output\","

#uci lat/lon

if which uci get system.@system[0].lat >/dev/null; then
	output=`uci get system.@system[0].lat`
else
	output=""
fi
echo "\"sys:lat\": \"$output\","
if which uci get system.@system[0].lon >/dev/null; then
	output=`uci get system.@system[0].lon`
else
	output=""
fi
echo "\"sys:lon\": \"$output\","


#Mailkontaktadresse
output=`uci get system.@system[0].contact_mail`
echo "\"ap:contact:mail\": \"$output\","

#sysinfo hardware
output=`grep -m 1 "cpu model" /proc/cpuinfo | cut -d ":" -f 2`
echo "\"sys:cpu_model\": \"$output\","

output=`cat /tmp/sysinfo/model`
echo "\"sys:machine\": \"$output\","

output=`grep -m 1 "system type" /proc/cpuinfo | cut -d ":" -f 2`
echo "\"sys:system_type\": \"$output\","
#sysinfo software

if which batctl >/dev/null; then
	output=`batctl -v | awk '{ print $2 }'`
	echo "\"sys:batman_version\": \"$output\","
else
	echo "\"batctl_missing\": \"yes\","
fi

output=`uname -r`
echo "\"sys:kernel_version\": \"$output\","

echo "}"
