#!/bin/sh
# fnetstat by RubenKelevra 2013-2015 - cyrond@gmail.com
# Lizenz: AGPL 3.0

#basic definitions
WORK_FOLDER="/tmp/"
BACKUP_FOLDER="/usr/share/fnetstat/"
MINUTLY="/bin/fnetstat_minutly"
DAILY="/bin/fnetstat_daily"
WIFISCAN="/bin/fnetstat_wifiscan"

BASIC_FILENAME="fnetstat"
DAILY_FILENAME="fnetstat_day"
WIFI_FILENAME="fnetstat_wifi"

PRINTHELP=0

mkdir -p $BACKUP_FOLDER

if [ ! -f $MINUTLY ]; then
	echo "$MINUTLY-Script was not found"
	exit 2
fi
if [ ! -f $DAILY ]; then
	echo "$DAILY-Script was not found"
	exit 2
fi
if [ ! -f $WIFISCAN ]; then
	echo "$WIFISCAN-Script was not found"
	exit 2
fi

if [ $# -eq 1 ]; then
	if [ "$1" == "cronjob" -o "$1" == "c" ]; then
		echo "Debug: starting normal cron-job run..."
	elif [ "$1" == "statistic" -o "$1" == "s" ]; then
		echo "Error: parameter not yet implemented." #fixme
		PRINTHELP=1
	else
		echo "Error: parameter not available." #fixme
		PRINTHELP=1
	fi
elif [ $# -gt 1 ]; then
	echo "Error: too many parameters."
	PRINTHELP=1
else
	PRINTHELP=1
fi

if [ $PRINTHELP -eq 1 ]; then
	echo ""
	echo "This is fnetstat."
	echo ""
	echo "Usage:"
	echo "       c / cronjob   - This keyword is used to enable the cronjob automatic"
	echo "                       behavior. Usually the script is started every minute and"
	echo "                       send data 4 times in an hour to the server."
	echo "       s / statistic - this prints an short statistic overview"
	echo ""
	echo " Use UCI for further configurations or edit /etc/config/fnetstat."
	echo ""
	echo " This program is copyrighted under AGPL 3.0"
	echo ""
	exit 0
fi

### begin ###

#uci vars
UCI_ULDIFF="fnetstat.cronjob.upload_diff"

ULDIFF=-1
FIRST_RUN_AFTER_BOOT=0

#check uci diff
if which uci get $UCI_ULDIFF >/dev/null; then
	ULDIFF=`uci get $UCI_ULDIFF`
	if [ $ULDIFF = "" ]; then
        	ULDIFF=-1
	fi
fi

if ! [ -f $WORK_FOLDER$BASIC_FILENAME ]; then 
	echo "Debug: random unique boot-hash hasn't been generated, we're running first time after boot"
	FIRST_RUN_AFTER_BOOT=1
fi

if [ $ULDIFF -eq -1 -o $FORCE_ULDIFF_UPDATE -eq 1 ]; then #we randomly generate a diff 
	echo "Debug: generating upload-diff..."
# elif #fixme check maximal diff to 60/x where x is uploads per hour
fi
